### ISSUE TITLE
userFollowing Temporarily response  403

### ISSUE THREAD

**Issue by yanagiragi** [akameco/pixiv-app-api#13]
- version:
- `node` version: 11.12.0
- `npm` (or `yarn`) version: npm 6.7.0

**Do you want to request a _feature_ or report a _bug_?:**

bug

**What is the current behavior?:**

calling userFollowing sometimes response 403, any idea why?

Below is the testing code.

```
const Pixiv = require('pixiv-app-api')

let pix = new Pixiv('ACCOUNT', 'PASSWORD')

pix.userFollowing('1655331')
    .catch(err => console.log(err))
    .then(data => console.log(data))

```

and here's some log:

```
root@8a393d977e7d:~/Pixiv-Downloader/bin# node test.js                                                              
{ Error: Request failed with status code 403                                                                        
    at createError (/root/Pixiv-Downloader/node_modules/axios/lib/core/createError.js:16:15)                        
    at settle (/root/Pixiv-Downloader/node_modules/axios/lib/core/settle.js:18:12)                                  
    at IncomingMessage.handleStreamEnd (/root/Pixiv-Downloader/node_modules/axios/lib/adapters/http.js:201:11)      
    at IncomingMessage.emit (events.js:202:15)                                                                      
    at endReadableNT (_stream_readable.js:1132:12)                                                                  
    at processTicksAndRejections (internal/process/next_tick.js:76:17)                                              
  config:                                                                                                           
   { adapter: [Function: httpAdapter],                                                                              
     transformRequest: { '0': [Function: transformRequest] },                                                       
     transformResponse: { '0': [Function: transformResponse] },                                                     
     timeout: 0,                                                                                                    
     xsrfCookieName: 'XSRF-TOKEN',                                                                                  
     xsrfHeaderName: 'X-XSRF-TOKEN',                                                                                
     maxContentLength: -1,                                                                                          
     validateStatus: [Function: validateStatus],                                                                    
     headers:                                                                                                       
      { Accept: 'application/json, text/plain, */*',                                                                
        Authorization: 'Bearer ***************************',                                        
        'App-OS': 'ios',                                                                                            
        'App-OS-Version': '9.3.3',                                                                                  
        'App-Version': '6.0.9',                                                                                     
        'User-Agent': 'axios/0.18.0' },                                                                             
     method: 'get',                                                                                                 
     baseURL: 'https://app-api.pixiv.net/',                                                                         
     url: 'https://app-api.pixiv.net/v1/user/following',                                                            
     params: { user_id: '1655331', restrict: 'public' },                                                            
     data: undefined },                                                                                             
  request:                                                                                                          
   ClientRequest {                                                                                                  
     _events:                                                                                                       
      [Object: null prototype] {                                                                                    
        socket: [Function],                                                                                         
        abort: [Function],                                                                                          
        aborted: [Function],                                                                                        
        error: [Function],                                                                                          
        timeout: [Function],                                                                                        
        prefinish: [Function: requestOnPrefinish] },                                                                
     _eventsCount: 6,                                                                                               
     _maxListeners: undefined,                                                                                      
     outputData: [],                                                                                                
     outputSize: 0,                                                                                                 
     writable: true,                                                                                                
     _last: true,                                                                                                   
     chunkedEncoding: false,                                                                                        
     shouldKeepAlive: false,                                                                                        
     useChunkedEncodingByDefault: false,                                                                            
     sendDate: false,                                                                                               
     _removedConnection: false,                                                                                     
     _removedContLen: false,                                                                                        
     _removedTE: false,                                                                                             
     _contentLength: 0,                                                                                             
     _hasBody: true,                                                                                                
     _trailer: '',                                                                                                  
     finished: true,                                                                                                
     _headerSent: true,                                                                                             
     socket:                                                                                                        
      TLSSocket {                                                                                                   
        _tlsOptions: [Object],                                                                                      
        _secureEstablished: true,                                                                                   
        _securePending: false,                                                                                      
        _newSessionPending: false,                                                                                  
        _controlReleased: true,                                                                                     
        _SNICallback: null,                                                                                         
        servername: 'app-api.pixiv.net',                                                                            
        alpnProtocol: false,                                                                                        
        authorized: true,                                                                                           
        authorizationError: null,                                                                                   
        encrypted: true,                                                                                            
        _events: [Object],                                                                                          
        _eventsCount: 9,                                                                                            
        connecting: false,                                                                                          
        _hadError: false,                                                                                           
        _parent: null,                                                                                              
        _host: 'app-api.pixiv.net',                                                                                 
        _readableState: [ReadableState],                                                                            
        readable: true,                                                                                             
        _maxListeners: undefined,                                                                                   
        _writableState: [WritableState],                                                                            
        writable: false,                                                                                            
        allowHalfOpen: false,                                                                                       
        _sockname: null,                                                                                            
        _pendingData: null,                                                                                         
        _pendingEncoding: '',                                                                                       
        server: undefined,                                                                                          
        _server: null,                                                                                              
        ssl: [TLSWrap],                                                                                             
        _requestCert: true,                                                                                         
        _rejectUnauthorized: true,                                                                                  
        parser: null,                                                                                               
        _httpMessage: [Circular],                                                                                   
        [Symbol(res)]: [TLSWrap],                                                                                   
        [Symbol(asyncId)]: 47,                                                                                      
        [Symbol(kHandle)]: [TLSWrap],                                                                               
        [Symbol(lastWriteQueueSize)]: 0,                                                                            
        [Symbol(timeout)]: null,                                                                                    
        [Symbol(kBytesRead)]: 0,                                                                                    
        [Symbol(kBytesWritten)]: 0,                                                                                 
        [Symbol(connect-options)]: [Object] },                                                                      
     connection:                                                                                                    
      TLSSocket {                                                                                                   
        _tlsOptions: [Object],                                                                                      
        _secureEstablished: true,                                                                                   
        _securePending: false,                                                                                      
        _newSessionPending: false,                                                                                  
        _controlReleased: true,                                                                                     
        _SNICallback: null,                                                                                         
        servername: 'app-api.pixiv.net',                                                                            
        alpnProtocol: false,                                                                                        
        authorized: true,                                                                                           
        authorizationError: null,                                                                                   
        encrypted: true,                                                                                            
        _events: [Object],                                                                                          
        _eventsCount: 9,                                                                                            
        connecting: false,                                                                                          
        _hadError: false,                                                                                           
        _parent: null,                                                                                              
        _host: 'app-api.pixiv.net',                                                                                 
        _readableState: [ReadableState],                                                                            
        readable: true,                                                                                             
        _maxListeners: undefined,                                                                                   
        _writableState: [WritableState],                                                                            
        writable: false,                                                                                            
        allowHalfOpen: false,                                                                                       
        _sockname: null,                                                                                            
        _pendingData: null,                                                                                         
        _pendingEncoding: '',                                                                                       
        server: undefined,                                                                                          
        _server: null,                                                                                              
        ssl: [TLSWrap],                                                                                             
        _requestCert: true,                                                                                         
        _rejectUnauthorized: true,                                                                                  
        parser: null,                                                                                               
        _httpMessage: [Circular],                                                                                   
        [Symbol(res)]: [TLSWrap],                                                                                   
        [Symbol(asyncId)]: 47,                                                                                      
        [Symbol(kHandle)]: [TLSWrap],                                                                               
        [Symbol(lastWriteQueueSize)]: 0,                                                                            
        [Symbol(timeout)]: null,                                                                                    
        [Symbol(kBytesRead)]: 0,                                                                                    
        [Symbol(kBytesWritten)]: 0,                                                                                 
        [Symbol(connect-options)]: [Object] },                                                                      
     _header:                                                                                                       
      'GET /v1/user/following?user_id=1655331&restrict=public HTTP/1.1\r\nAccept: application/json, text/plain, */*\
\nAuthorization: Bearer ***************************\r\nApp-OS: ios\r\nApp-OS-Version: 9.3.3\r\nApp-V
rsion: 6.0.9\r\nUser-Agent: axios/0.18.0\r\nHost: app-api.pixiv.net\r\nConnection: close\r\n\r\n',                  
     _onPendingData: [Function: noopPendingOutput],                                                                 
     agent:                                                                                                         
      Agent {                                                                                                       
        _events: [Object],                                                                                          
        _eventsCount: 1,                                                                                            
        _maxListeners: undefined,                                                                                   
        defaultPort: 443,                                                                                           
        protocol: 'https:',                                                                                         
        options: [Object],                                                                                          
        requests: {},                                                                                               
        sockets: [Object],                                                                                          
        freeSockets: {},                                                                                            
        keepAliveMsecs: 1000,                                                                                       
        keepAlive: false,                                                                                           
        maxSockets: Infinity,                                                                                       
        maxFreeSockets: 256,                                                                                        
        maxCachedSessions: 100,                                                                                     
        _sessionCache: [Object] },                                                                                  
     socketPath: undefined,                                                                                         
     timeout: undefined,                                                                                            
     method: 'GET',                                                                                                 
     path: '/v1/user/following?user_id=1655331&restrict=public',                                                    
     _ended: true,                                                                                                  
     res:                                                                                                           
      IncomingMessage {                                                                                             
        _readableState: [ReadableState],                                                                            
        readable: false,                                                                                            
        _events: [Object],                                                                                          
        _eventsCount: 3,                                                                                            
        _maxListeners: undefined,                                                                                   
        socket: [TLSSocket],                                                                                        
        connection: [TLSSocket],                                                                                    
        httpVersionMajor: 1,                                                                                        
        httpVersionMinor: 1,                                                                                        
        httpVersion: '1.1',                                                                                         
        complete: true,                                                                                             
        headers: [Object],                                                                                          
        rawHeaders: [Array],                                                                                        
        trailers: {},                                                                                               
        rawTrailers: [],                                                                                            
        aborted: false,                                                                                             
        upgrade: false,                                                                                             
        url: '',                                                                                                    
        method: null,                                                                                               
        statusCode: 403,                                                                                            
        statusMessage: 'Forbidden',                                                                                 
        client: [TLSSocket],                                                                                        
        _consuming: false,                                                                                          
        _dumped: false,                                                                                             
        req: [Circular],                                                                                            
        responseUrl:                                                                                                
         'https://app-api.pixiv.net/v1/user/following?user_id=1655331&restrict=public',                             
        redirects: [] },                                                                                            
     aborted: false,                                                                                                
     timeoutCb: null,                                                                                               
     upgradeOrConnect: false,                                                                                       
     parser: null,                                                                                                  
     maxHeadersCount: null,                                                                                         
     _redirectable:                                                                                                 
      Writable {                                                                                                    
        _writableState: [WritableState],                                                                            
        writable: true,                                                                                             
        _events: [Object],                                                                                          
        _eventsCount: 2,                                                                                            
        _maxListeners: undefined,                                                                                   
        _options: [Object],                                                                                         
        _ended: true,                                                                                               
        _ending: true,                                                                                              
        _redirectCount: 0,                                                                                          
        _redirects: [],                                                                                             
        _requestBodyLength: 0,                                                                                      
        _requestBodyBuffers: [],                                                                                    
        _onNativeResponse: [Function],                                                                              
        _currentRequest: [Circular],                                                                                
        _currentUrl:                                                                                                
         'https://app-api.pixiv.net/v1/user/following?user_id=1655331&restrict=public' },                           
     [Symbol(isCorked)]: false,                                                                                     
     [Symbol(outHeadersKey)]:                                                                                       
      [Object: null prototype] {                                                                                    
        accept: [Array],                                                                                            
        authorization: [Array],                                                                                     
        'app-os': [Array],                                                                                          
        'app-os-version': [Array],                                                                                  
        'app-version': [Array],                                                                                     
        'user-agent': [Array],                                                                                      
        host: [Array] } },                                                                                          
  response:                                                                                                         
   { status: 403,                                                                                                   
     statusText: 'Forbidden',                                                                                       
     headers:                                                                                                       
      { server: 'nginx',                                                                                            
        date: 'Thu, 28 Mar 2019 19:36:05 GMT',                                                                      
        'content-type': 'application/json; charset=utf-8',                                                          
        'content-length': '90',                                                                                     
        connection: 'close',                                                                                        
        'x-userid': '21780164',                                                                                     
        vary: 'X-UserId',                                                                                           
        'x-content-type-options': 'nosniff',                                                                        
        'strict-transport-security': 'max-age=31536000' },                                                          
     config:                                                                                                        
      { adapter: [Function: httpAdapter],                                                                           
        transformRequest: [Object],                                                                                 
        transformResponse: [Object],                                                                                
        timeout: 0,                                                                                                 
        xsrfCookieName: 'XSRF-TOKEN',                                                                               
        xsrfHeaderName: 'X-XSRF-TOKEN',                                                                             
        maxContentLength: -1,                                                                                       
        validateStatus: [Function: validateStatus],                                                                 
        headers: [Object],                                                                                          
        method: 'get',                                                                                              
        baseURL: 'https://app-api.pixiv.net/',                                                                      
        url: 'https://app-api.pixiv.net/v1/user/following',                                                         
        params: [Object],                                                                                           
        data: undefined },                                                                                          
     request:                                                                                                       
      ClientRequest {                                                                                               
        _events: [Object],                                                                                          
        _eventsCount: 6,                                                                                            
        _maxListeners: undefined,                                                                                   
        outputData: [],                                                                                             
        outputSize: 0,                                                                                              
        writable: true,                                                                                             
        _last: true,                                                                                                
        chunkedEncoding: false,                                                                                     
        shouldKeepAlive: false,                                                                                     
        useChunkedEncodingByDefault: false,                                                                         
        sendDate: false,                                                                                            
        _removedConnection: false,                                                                                  
        _removedContLen: false,                                                                                     
        _removedTE: false,                                                                                          
        _contentLength: 0,                                                                                          
        _hasBody: true,                                                                                             
        _trailer: '',                                                                                               
        finished: true,                                                                                             
        _headerSent: true,                                                                                          
        socket: [TLSSocket],                                                                                        
        connection: [TLSSocket],                                                                                    
        _header:                                                                                                    
         'GET /v1/user/following?user_id=1655331&restrict=public HTTP/1.1\r\nAccept: application/json, text/plain, *
*\r\nAuthorization: Bearer ****************************\r\nApp-OS: ios\r\nApp-OS-Version: 9.3.3\r\nAp
-Version: 6.0.9\r\nUser-Agent: axios/0.18.0\r\nHost: app-api.pixiv.net\r\nConnection: close\r\n\r\n',               
        _onPendingData: [Function: noopPendingOutput],                                                              
        agent: [Agent],                                                                                             
        socketPath: undefined,                                                                                      
        timeout: undefined,                                                                                         
        method: 'GET',                                                                                              
        path: '/v1/user/following?user_id=1655331&restrict=public',                                                 
        _ended: true,                                                                                               
        res: [IncomingMessage],                                                                                     
        aborted: false,                                                                                             
        timeoutCb: null,                                                                                            
        upgradeOrConnect: false,                                                                                    
        parser: null,                                                                                               
        maxHeadersCount: null,                                                                                      
        _redirectable: [Writable],                                                                                  
        [Symbol(isCorked)]: false,                                                                                  
        [Symbol(outHeadersKey)]: [Object] },                                                                        
     data: { error: [Object] } } }                                                                                  
undefined                                                                                                           
root@8a393d977e7d:~/Pixiv-Downloader/bin# node test.js                                                              
{ userPreviews:                                                                                                     
   [ { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [], novels: [], isMuted: false },                                                   
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false },                                              
     { user: [Object], illusts: [Array], novels: [], isMuted: false } ],                                            
  nextUrl:                                                                                                          
   'https://app-api.pixiv.net/v1/user/following?user_id=1655331&restrict=public&offset=30' }                        
```

I replaced the token in request header, hope it doesn't matters.

Sorry for the long log, basically it tells that the same code run different results, one works normally and one don't. The two code are run sequentially. The second code is runned about 3~5 minutes after the first code done.

I have tried several times, but I can't get the pattern whether it works or not.

The only reason I can guess is it may limited the api requests (so I thinks it's Pixiv's problem), but I'm not sure about that.

**What is the expected behavior?:**

output partial user followings

**Suggested solution:**

Not a clue how this bug produces, sorry about that.

**Comment by akameco** [comment]
@yanagiragi  Repeated logins may restrict the API. There is no way to get around this. It is recommended that you do not log in again as much as possible.

**Comment by akameco** [comment]
This is not a problem with `pixiv-appi-api`. Thank you for the report 😄
